
custom_corrections =  {
    "what": "What",
    "is": "Is",
    "where": "Where",
    "how": "How",
    "campus": "Campus",
    "compass": "Compass",
    "campus compass logo": "Campus Compass Logo",
    "campus compass": "Campus Compass",
    "home": "Home",
    "about": "About",
    "courses": "Courses",
    "faq": "FAQ",
    "contact us": "Contact Us",
    "terms and conditions": "Terms and Conditions",
    "login": "Login",
    "sign up": "Sign Up",
    "universities & degree courses in sri lanka": "Universities & Degree Courses in Sri Lanka",
    "search": "Search",
    "search by university, a/l stream or course": "Search by University, A/L Stream, or Course",
    "select university": "Select University",
    "select stream": "Select Stream",
    "select course": "Select Course",
    "university of sri jayawardanapura": "University of Sri Jayawardanapura",
    "university of kelaniya": "University of Kelaniya",
    "university of colombo": "University of Colombo",
    "university of jaffna": "University of Jaffna",
    "university of ruhuna": "University of Ruhuna",
    "university of peradeniya": "University of Peradeniya",
    "eastern university, sri lanka": "Eastern University, Sri Lanka",
    "sabaragamuwa university of sri lanka": "Sabaragamuwa University of Sri Lanka",
    "uva wellassa university of sri lanka": "Uva Wellassa University of Sri Lanka",
    "rajarata university of sri lanka": "Rajarata University of Sri Lanka",
    "university of moratuwa": "University of Moratuwa",
    "south eastern university of sri lanka": "South Eastern University of Sri Lanka",
    "wayamba university of sri lanka": "Wayamba University of Sri Lanka",
    "university of vavuniya, sri lanka": "University of Vavuniya, Sri Lanka",
    "gampaha wickramarachchi university of indigenous medicine, sri lanka": "Gampaha Wickramarachchi University of Indigenous Medicine, Sri Lanka",
    "university of the visual & performing arts": "University of the Visual & Performing Arts",
    "the open university of sri lanka": "The Open University of Sri Lanka",
    # Additional entries can be added below
    "university": "University",
    "degree": "Degree",
    "courses": "Courses",
    "student": "Student",
    "apply": "Apply",
    "admission": "Admission",
    "results": "Results",
    "contact": "Contact",
    "support": "Support",
    "graduate": "Graduate",
    "program": "Program",
    "faculty": "Faculty",
    "department": "Department",
    "scholarship": "Scholarship",
    "exam": "Exam",
    "study": "Study",
    "campus life": "Campus Life",
    "curriculum": "Curriculum",
    "research": "Research",
    "faculty of engineering": "Faculty of Engineering",
    "faculty of science": "Faculty of Science",
    "faculty of arts": "Faculty of Arts",
    "university admission": "University Admission",
    "academic program": "Academic Program",
    "accommodation": "Accommodation",
    "students' union": "Students' Union",
    "international students": "International Students",
    "whta": "What",
    "iw": "Is",
    "wher": "Where",
    "hoow": "How",
    "camus": "Campus",
    "comapss": "Compass",
    "campus comapss logo": "Campus Compass Logo",
    "campus compas": "Campus Compass",
    "hom": "Home",
    "abou": "About",
    "cours": "Courses",
    "faqs": "FAQ",
    "cotact us": "Contact Us",
    "terma and conditions": "Terms and Conditions",
    "logn": "Login",
    "sin up": "Sign Up",
    "universitiess & degree courses in sri lanka": "Universities & Degree Courses in Sri Lanka",
    "serach": "Search",
    "serach by university, a/l stream or course": "Search by University, A/L Stream, or Course",
    "select univesity": "Select University",
    "selct stream": "Select Stream",
    "selecct course": "Select Course",
    "univrsity of sri jayawardanapura": "University of Sri Jayawardanapura",
    "univesity of kelaniya": "University of Kelaniya",
    "unversity of colombo": "University of Colombo",
    "unversity of jaffna": "University of Jaffna",
    "univeristy of ruhuna": "University of Ruhuna",
    "unversity of peradeniya": "University of Peradeniya",
    "eastern unversity, sri lanka": "Eastern University, Sri Lanka",
    "sabaragamua university of sri lanka": "Sabaragamuwa University of Sri Lanka",
    "uva wellasa university of sri lanka": "Uva Wellassa University of Sri Lanka",
    "rajarata unviersity of sri lanka": "Rajarata University of Sri Lanka",
    "univeristy of moratuwa": "University of Moratuwa",
    "south estern university of sri lanka": "South Eastern University of Sri Lanka",
    "waymaba university of sri lanka": "Wayamba University of Sri Lanka",
    "university of vavuniya, sri lanaka": "University of Vavuniya, Sri Lanka",
    "gampaha wickramarachchi univeristy of indigenous medicine, sri lanka": "Gampaha Wickramarachchi University of Indigenous Medicine, Sri Lanka",
    "universisty of the visual & performing arts": "University of the Visual & Performing Arts",
    "the opn university of sri lanka": "The Open University of Sri Lanka",
    "univesity": "University",
    "degee": "Degree",
    "coruses": "Courses",
    "sutdent": "Student",
    "aply": "Apply",
    "admmison": "Admission",
    "result": "Results",
    "contct": "Contact",
    "suport": "Support",
    "gradute": "Graduate",
    "prgram": "Program",
    "faculity": "Faculty",
    "deprtment": "Department",
    "sholarship": "Scholarship",
    "exm": "Exam",
    "stuy": "Study",
    "campus lif": "Campus Life",
    "curiculum": "Curriculum",
    "reaserch": "Research",
    "faculity of engineering": "Faculty of Engineering",
    "faculity of science": "Faculty of Science",
    "faculity of arts": "Faculty of Arts",
    "univesity admission": "University Admission",
    "acadamic program": "Academic Program",
    "accomadation": "Accommodation",
    "studnt union": "Students' Union",
    "internationl students": "International Students"
}
